spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/vwx
    username: sa
    password: vwx
    driver-class-name: org.h2.Driver
  jpa:
#    hibernate.hbm2ddl.auto: create
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug